version: '3.8'

services:
  # Nginx リバースプロキシ
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node-server
      - flask-server
    networks:
      - web-network

  # Node.js サーバー
  node-server:
    build:
      context: ./node-app
      dockerfile: Dockerfile
    container_name: node-app
    expose:
      - "3000"
    networks:
      - web-network
    environment:
      - NODE_ENV=production

  # Flask サーバー
  flask-server:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    container_name: flask-app
    expose:
      - "5000"
    networks:
      - web-network
    environment:
      - FLASK_ENV=production

networks:
  web-network:
    driver: bridge